"""leaderboard name change to gameResult

Revision ID: 801fa7aa19f9
Revises: 5fc0a6b5a51b
Create Date: 2024-05-02 02:06:32.253850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801fa7aa19f9'
down_revision = '5fc0a6b5a51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_result',
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('puzzle_id')
    )
    op.drop_table('leader_board')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leader_board',
    sa.Column('puzzle_id', sa.INTEGER(), nullable=False),
    sa.Column('word', sa.VARCHAR(length=128), nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('time_spent', sa.INTEGER(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('puzzle_id')
    )
    op.drop_table('game_result')
    # ### end Alembic commands ###
