"""word table creation

Revision ID: bae77ee1dfd9
Revises: 801fa7aa19f9
Create Date: 2024-05-02 02:11:26.202059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae77ee1dfd9'
down_revision = '801fa7aa19f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('word_length', sa.Integer(), nullable=True),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('word_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    # ### end Alembic commands ###
