"""Basic Schema

Revision ID: ee5a60d123f3
Revises: 
Create Date: 2024-05-02 04:37:15.494481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee5a60d123f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('word',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('word_length', sa.Integer(), nullable=True),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('word_id')
    )
    op.create_table('puzzle',
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.word_id'], ),
    sa.PrimaryKeyConstraint('puzzle_id')
    )
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_puzzle_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_puzzle_word_id'), ['word_id'], unique=False)

    op.create_table('game_result',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('puzzle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzle.puzzle_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    with op.batch_alter_table('game_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_result_puzzle_id'), ['puzzle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_result_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_result_user_id'))
        batch_op.drop_index(batch_op.f('ix_game_result_puzzle_id'))

    op.drop_table('game_result')
    with op.batch_alter_table('puzzle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_puzzle_word_id'))
        batch_op.drop_index(batch_op.f('ix_puzzle_user_id'))

    op.drop_table('puzzle')
    op.drop_table('word')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
